/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
